### PR TITLE
fix: fixed bug in which user can submit quiz over the maximum limit allowed

### LINKED ISSUE #1314: Bug: Quiz Maximum Attempts not working correctly
User is able to bypass Maximum Quiz attempts by either

1. Not refreshing the page
2. Or duplicating the quiz tab multiple times and then submitting it.

In both cases, User can bypass quiz submission maximum limit.

**Case 1**

https://github.com/user-attachments/assets/1ee2cda4-16da-4a19-9719-c4e605d164b2

**Case 2**

https://github.com/user-attachments/assets/7c34cfec-c2ab-40bb-999c-e730da81c71b

### PR DESCRIPTION
**Pull request by FahidLatheef**
This PR includes

- Validation for quiz submission limit (both in backend and frontend)
- Fixed some spelling typos
- Fixed an issue while running yarn dev

Closes #1314

### CODE REVIEW

**Comment by FahidLatheef** [comment]
Fixes https://github.com/frappe/lms/issues/1314

**Case1 Fix**

https://github.com/user-attachments/assets/5a331dd1-901c-42fb-b701-11249f3eabf8

**Case2 Fix**

https://github.com/user-attachments/assets/1d30a4bd-89b8-4ce2-87c7-1405e87e54c3

File: frontend/src/router.js [hunk 1]
```diff
@@ -219,7 +219,7 @@ let router = createRouter({
 
 router.beforeEach(async (to, from, next) => {
 	const { userResource } = usersStore()
-	const { isLoggedIn } = sessionStore()
+	let { isLoggedIn } = sessionStore()
```
Comment (pateljannat) [inline frontend/src/router.js:222]: @FahidLatheef why this change?
